truncate "ItemSubcategories" CASCADE;

ALTER SEQUENCE "ItemSubcategories_Id_seq" RESTART WITH 1;

insert into "ItemSubcategories"("Name", "ItemCategoryId")
values
('Helmet', 1),
('Mask', 1),
('Body Armor', 1),
('Unarmored Chest Rig', 1),
('Armored Rig', 1),
('Backpack', 1),
('Headset', 1),
('Gas Mask', 1),
('Sights', 2),
('Magazine', 2),
('Front Grips', 2),
('Rear Grips', 2),
('Stock', 2),
('Muzzle', 2),
('Lazer Sight', 2),
('Barrel', 2),
('Handguard', 2),
('Receiver', 2),
('Rail', 2),
('Gas Block', 2),
('Gun Bolt', 2),
('Flashlight', 2),
('Assault Rifles', 3),
('Submachine Guns', 3),
('Shotguns', 3),
('Light Machine Guns', 3),
('Bolt-Action Rifles', 3),
('Marksman Rifles', 3),
('Carbines', 3),
('Pistol', 3),
('5.45x39', 4),
('5.56x45', 4),
('5.7x28', 4),
('5.8x42', 4),
('7.62x25', 4),
('7.62x39', 4),
('7.62x51', 4),
('7.62x54', 4),
('9x19', 4),
('9x39', 4),
('12x70', 4),
('.44', 4),
('.45', 4),
('.338', 4),
('Medicine', 5),
('Treatments', 5),
('Medkits', 5),
('Stimulants', 5),
('Throwables', 6),
('Farm', 7),
('Northridge', 7),
('Valley', 7),
('Armory', 7),
('Tv Station', 7),
('Flammables', 8),
('Building Materials', 8),
('Computer Parts', 8),
('Energy Items', 8),
('Tools', 8),
('Household Items', 8),
('Miscellaneous Medical Items', 8),
('Collectibles', 8),
('Paper', 8),
('Instruments', 8),
('Miscellaneous Military Items', 8),
('Boss Token', 8),
('Electronics', 8),
('Beverages', 9),
('Food', 9);

select * from "ItemSubcategories";